### ISSUE TITLE
PHP 8 error

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/Module-Simple-billing#17]
Forum thread https://opengamepanel.org/forum/viewthread.php?thread_id=8284&pid=42571#post_42571

```
Fatal error: Uncaught TypeError: array_multisort(): Argument #1 ($array) must be an array or a sort flag in /var/www/u2515/data/www/redacted_domain/modules/simple-billing/shop_guest.php:71 Stack trace: #0 /var/www/u2515/data/www/redacted_domain/modules/simple-billing/shop_guest.php(71): array_multisort(NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, false) #1 /var/www/u2515/data/www/redacted_domain/includes/navig.php(106): exec_ogp_module() #2 /var/www/u2515/data/www/redacted_domain/includes/navig.php(27): navigation() #3 /var/www/u2515/data/www/redacted_domain/index.php(121): include('/var/www/u2515...') #4 /var/www/u2515/data/www/redacted_domain/index.php(195): heading() #5 /var/www/u2515/data/www/redacted_domain/index.php(88): ogpHome() #6 {main} thrown in /var/www/u2515/data/www/redacted_domain/modules/simple-billing/shop_guest.php on line 71
```

Probably needs the same set of fixes that have been done recently on various pages and modules.

**Comment by Zinnorov** [comment]
Thank you for posting the issue here!
